// IBS-vänliga matlådor. Mängder är gram per portion (som tillagad vikt där det gäller ris, pasta, potatis och kött).
// Alla ingredienser hålls inom low-FODMAP-gränserna i foods.js (kontrolleras av tests/check.js).

const RECIPES = [
  {
    id: "kyckling-ris",
    title: "Kyckling, ris och ugnsrostade grönsaker",
    meal: "Lunch/Middag",
    tags: ["Proteinrik", "Enkel"],
    why: "Milda råvaror utan lök och vitlök. Ris är skonsamt för magen.",
    ingredients: [
      { id: "kyckling", g: 150 },
      { id: "ris", g: 200 },
      { id: "morot", g: 100 },
      { id: "zucchini", g: 60 },
      { id: "olivolja", g: 10 },
    ],
    extras: ["Salt, peppar", "Paprikapulver (rent, utan lökpulver)"],
    steps: [
      "Sätt ugnen på 200 °C.",
      "Skär morot och zucchini i bitar. Blanda med hälften av oljan.",
      "Krydda kycklingen och pensla med resten av oljan.",
      "Rosta kyckling och grönsaker i 20–25 minuter.",
      "Koka riset. Dela upp i lådor.",
    ],
  },
  {
    id: "lax-potatis",
    title: "Lax med potatis och broccoli",
    meal: "Middag",
    tags: ["Omega-3", "Enkel"],
    why: "Fisk och potatis har inga FODMAP. Broccolin håller sig under gränsen.",
    ingredients: [
      { id: "lax", g: 130 },
      { id: "potatis", g: 250 },
      { id: "broccoli", g: 70 },
      { id: "olivolja", g: 10 },
    ],
    extras: ["Citron", "Färsk dill", "Salt, peppar"],
    steps: [
      "Koka potatisen i saltat vatten tills den är mjuk.",
      "Lägg laxen på plåt. Ringla över olja, salt och peppar.",
      "Baka laxen i 12–15 minuter på 200 °C.",
      "Ånga broccolin i 3–4 minuter.",
      "Toppa med dill och citron. Dela upp i lådor.",
    ],
  },
  {
    id: "kottfarssas",
    title: "Köttfärssås med glutenfri pasta",
    meal: "Middag",
    tags: ["Proteinrik", "Mättande"],
    why: "Vitlöksolja ger smak utan fruktaner. Glutenfri pasta är skonsammare än vete.",
    ingredients: [
      { id: "notfars", g: 120 },
      { id: "gfpasta", g: 140 },
      { id: "krossadtomat", g: 90 },
      { id: "morot", g: 50 },
      { id: "vitlokso", g: 10 },
    ],
    extras: ["Basilika, oregano", "Salt, peppar"],
    steps: [
      "Hetta upp vitlöksoljan i en panna.",
      "Stek färsen tills den är genomstekt.",
      "Riv moroten och rör ner den.",
      "Tillsätt krossade tomater och kryddor. Sjud i 15 minuter.",
      "Koka pastan. Blanda eller lägg separat i lådorna.",
    ],
  },
  {
    id: "quinoasallad",
    title: "Quinoasallad med kyckling och fetaost",
    meal: "Lunch",
    tags: ["Kall låda", "Proteinrik"],
    why: "Bra som kall lunch. Fetaosten är låg i laktos.",
    ingredients: [
      { id: "kyckling", g: 120 },
      { id: "quinoa", g: 150 },
      { id: "gurka", g: 100 },
      { id: "tomat", g: 70 },
      { id: "feta", g: 30 },
      { id: "olivolja", g: 10 },
    ],
    extras: ["Citronsaft", "Färsk persilja", "Salt, peppar"],
    steps: [
      "Koka quinoan och låt den svalna.",
      "Skär gurka, tomat och kyckling i bitar.",
      "Blanda allt med olja, citronsaft och kryddor.",
      "Smula fetaost över.",
      "Dela upp i lådor. Håll kallt.",
    ],
  },
  {
    id: "tofu-wok",
    title: "Tofuwok med ris",
    meal: "Lunch/Middag",
    tags: ["Vegetarisk", "Snabb"],
    why: "Fast tofu är lågt i FODMAP. Salladslökens gröna del ger lökssmak.",
    ingredients: [
      { id: "tofu", g: 150 },
      { id: "ris", g: 200 },
      { id: "morot", g: 80 },
      { id: "paprika", g: 40 },
      { id: "salladslok", g: 20 },
      { id: "sojasas", g: 15 },
      { id: "olivolja", g: 10 },
    ],
    extras: ["Ingefära (färsk)", "Peppar"],
    steps: [
      "Pressa tofun torr och skär i kuber.",
      "Stek tofun i olja tills den är gyllene.",
      "Tillsätt morot, paprika och ingefära. Wokka i 4–5 minuter.",
      "Tillsätt sojasås och salladslök.",
      "Servera på kokt ris. Dela upp i lådor.",
    ],
  },
  {
    id: "aggmuffins",
    title: "Äggmuffins med spenat och ost",
    meal: "Frukost/Mellanmål",
    tags: ["Vegetarisk", "Proteinrik", "Frysbar"],
    why: "Ägg tolereras oftast bra. Muffinsen går att frysa.",
    ingredients: [
      { id: "agg", g: 150 },
      { id: "spenat", g: 40 },
      { id: "tomat", g: 40 },
      { id: "hardost", g: 30 },
      { id: "olivolja", g: 5 },
    ],
    extras: ["Salt, peppar"],
    steps: [
      "Sätt ugnen på 180 °C. Smörj en muffinsform med olja.",
      "Vispa ägg med salt och peppar.",
      "Hacka spenat och tomat. Fördela i formen med riven ost.",
      "Häll över äggsmeten.",
      "Grädda i 18–20 minuter. Svalna och dela upp.",
    ],
  },
  {
    id: "kalkonbullar",
    title: "Kalkonbullar med potatismos",
    meal: "Middag",
    tags: ["Proteinrik", "Mättande"],
    why: "Havregryn binder bullarna utan vetebröd. Mos görs med laktosfri mjölk.",
    ingredients: [
      { id: "kalkon", g: 130 },
      { id: "potatis", g: 250 },
      { id: "lfmjolk", g: 40 },
      { id: "smor", g: 10 },
      { id: "morot", g: 70 },
      { id: "havregryn", g: 15 },
    ],
    extras: ["Salt, peppar", "Timjan"],
    steps: [
      "Blanda kalkonfärs, havregryn, salt och timjan. Forma bullar.",
      "Stek eller baka bullarna tills de är genomstekta.",
      "Koka potatis och morot. Mosa potatisen med mjölk och smör.",
      "Dela upp bullar, mos och morötter i lådor.",
    ],
  },
  {
    id: "tonfiskssallad",
    title: "Tonfisk- och potatissallad",
    meal: "Lunch",
    tags: ["Kall låda", "Snabb"],
    why: "Enkel och mild. Inga lök-FODMAP eftersom bara den gröna delen används.",
    ingredients: [
      { id: "tonfisk", g: 100 },
      { id: "potatis", g: 250 },
      { id: "gurka", g: 60 },
      { id: "agg", g: 50 },
      { id: "olivolja", g: 10 },
      { id: "salladslok", g: 15 },
    ],
    extras: ["Citronsaft", "Dijonsenap (kolla ingredienser)", "Salt, peppar"],
    steps: [
      "Koka potatis och ägg. Låt svalna.",
      "Skär potatis, gurka och ägg i bitar.",
      "Blanda med tonfisk, olja, citronsaft och salladslök.",
      "Dela upp i lådor. Håll kallt.",
    ],
  },
  {
    id: "overnight-oats",
    title: "Overnight oats med blåbär och chia",
    meal: "Frukost",
    tags: ["Vegetarisk", "Ingen tillagning"],
    why: "Havre och chia ger löslig fiber. Passar bra vid förstoppning.",
    ingredients: [
      { id: "havregryn", g: 45 },
      { id: "lfmjolk", g: 150 },
      { id: "chia", g: 15 },
      { id: "blabar", g: 35 },
      { id: "jordnotssmor", g: 10 },
    ],
    extras: ["Kanel"],
    steps: [
      "Blanda havregryn, chiafrön, mjölk och kanel i en burk.",
      "Ställ i kylen över natten.",
      "Toppa med blåbär och jordnötssmör på morgonen.",
    ],
  },
];

if (typeof module !== "undefined") module.exports = { RECIPES };
